{% set name = "fenicsx-pulse" %}
{% set python_min = "3.10" %}
{% set version = "0.5.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fenicsx_pulse-{{ version }}.tar.gz
  sha256: 82243ae3c13a2c4f49662e92c60554c617c72560e81f36d7d34cfc7b8275f568

build:
  number: 0
  noarch: python
  entry_points:
    - "pulse=pulse.cli:main"
  script: python -m pip install -v --no-deps .

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy
    - pint
    - rich
    - rich-argparse
    - scifem
    - fenics-dolfinx

test:
  requires:
    - python {{ python_min }}
    - pip
  imports:
    - fenicsx_pulse
  commands:
    - pulse --help
    - pip check


about:
  home: https://github.com/finsberg/fenicsx-pulse
  summary: Next generation cardiac mechanics solver based on FEniCSx
  license: MIT
  license_file: LICENSE
  doc_url: https://finsberg.github.io/fenicsx-pulse/
  dev_url: https://github.com/finsberg/fenicsx-pulse

extra:
  recipe-maintainers:
    - finsberg
